import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  productsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products',
    },
  ],

  standardsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'standards',
    },
  ],
  
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};

export default sidebars;