import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Thanh bên cho menu Tiêu chuẩn (Tự động lấy tất cả file trong thư mục docs/tieu-chuan)
  standardsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'standards',
    },
  ],
  
  // Thanh bên cho menu Hướng dẫn (Tự động lấy tất cả file trong thư mục docs/huong-dan)
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};

export default sidebars;